/*
 * MRCC_Program.c
 *
 *  Created on: May 10, 2022 3:59:38 AM RCC_DRIVER_PRO
 *      Author: mahmoud ramadan
 */
#include"../../LIB/LSTD_TYPES.h"
#include"../../LIB/LBIT_MATH.h"
#include"MRCC_Private.h"
#include"MRCC_Config.h"
#include"MRCC_Interface.h"

void MRCC_VidInitSystemClock(void)
{
	/*Clear Register At first*/
	RCC_CR=0x00000083;
	RCC_CFGR=0x00000000;
	/*choose system clock from option
	 * 1-HSI
	 * 2-HSE_CRYSTAL
	 * 3-HSE_RC
	 * 4-PLL*/
#if SYSTEM_CLOCK== RCC_HSI
	SET_BIT(RCC_CR,RCC_CR_HSION);
	/*wait till ready*/
	while(!(RCC_CR & (1<<RCC_CR_HSIRDY)));
	CLR_BIT(RCC_CFGR,RCC_CFGR_SW0);
	CLR_BIT(RCC_CFGR,RCC_CFGR_SW1);
#elif SYSTEM_CLOCK == RCC_HSE_CRYSTAL
   SET_BIT(RCC_CR,RCC_CR_HSEON);
   while(!(RCC_CR &(1<<RCC_CR_HSERDY)));
   CLR_BIT(RCC_CR,RCC_CR_HSEBYP);
   CLR_BIT(RCC_CFGR,RCC_CFGR_SW1);
   SET_BIT(RCC_CFGR,RCC_CFGR_SW0);
#elif SYSTEM_CLOCK== RCC_HSE_RC
   SET_BIT(RCC_CR,RCC_CR_HSION);
   while(!(RCC_CR & (1<<RCC_CR_HSIRDY)));
   SET_BIT(RCC_CR,RCC_CR_HSEBYP);
   CLR_BIT(RCC_CFGR,RCC_CFGR_SW1);
   SET_BIT(RCC_CFGR,RCC_CFGR_SW0);
#elif SYSTEM_CLOCK== RCC_PLL
   RCC_CFGR &= ~(15 << RCC_CFGR_PLLMUL0);
   RCC_CFGR|=((RCC_PLL_MUL -2)<< RCC_CFGR_PLLMUL0);
	#if RCC_PLL_SOURCE ==RCC_PLL_HSI_SOURCE_BY2
   	   SET_BIT(RCC_CR,RCC_CR_HSION);
   	   CLR_BIT(RCC_CFGR,RCC_CFGR_PLLSRC);
	#elif RCC_PLL_SOURCE==RCC_PLL_HSE_SOURCE
   	   SET_BIT(RCC_CR,RCC_CR_HSION);
   	   SET_BIT(RCC_CFGR,RCC_CFGR_PLLSRC);
   	#elif RCC_PLL_SOURCE==RCC_PLL_HSE_SOURCE_BY2
   	   SET_BIT(RCC_CR,RCC_CR_HSION);
   	   SET_BIT(RCC_CFGR,RCC_CFGR_PLLXTPRE);
   	   SET_BIT(RCC_CFGR,RCC_CFGR_PLLSRC);
   #error"Configuration is not Valid"
	#endif
   	   SET_BIT(RCC_CR,RCC_CR_PLLON);
   	   while(!(RCC_CR & (1<<RCC_CR_PLLRDY)));
   	   CLR_BIT(RCC_CFGR,RCC_CFGR_SW0);
   	   SET_BIT(RCC_CFGR,RCC_CFGR_SW1);
#error"Configuration is not Valid"
#endif
   	   /*SET correction factor*/
#if RCC_HSI_CORRECTION!=0
   	   RCC_CR &=~(31<<RCC_CR_HSITRIM0)
   	   RCC_CR |=((RCC_HSI_CORRECTION+16)<<RCC_CR_HSITRIM0);
#endif
   	   /*MCO PIN outputs*/
#if RCC_MCO_PIN ==NO_SOUCRE
   	   CLR_BIT(RCC_CFGR,RCC_CFGR_MCO_2);
#elif RCC_MCO_PIN==HSI_SOURCE
   	   SET_BIT(RCC_CR,RCC_CR_HSION);
   	   SET_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_0);
   	   CLR_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_1);
   	   SET_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_2);
#elif RCC_MCO_PIN==HSE_SOURCE
   	   SET_BIT(RCC_CR,RCC_CR_HSEON);
   	   CLR_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_0);
   	   SET_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_1);
   	   SET_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_2);
#elif RCC_MCO_PIN==PLL_SOURCE
   	SET_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_0);
   	SET_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_2);
   	SET_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_2);
#elif RCC_MCO_PIN==SYSTME_SOURCE
   	CLR_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_0);
   	CLR_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_1);
   	SET_BIT(RCC_CFGR,RCC_RCC_CFGR_MCO_2);
#else
#error"MCO PIN option is Not Valid"
#endif
   	/*Clock security options */
#if CSS_ON==ENABLE
   	SET_BIT(RCC_CR,RCC_CR_CSSON);
#elif CSS_ON ==DISABLE
   	CLR_BIT(RCC_CR,RCC_CR_CSSON);
#else
#error"CSS options Is Not Valid"
#endif
   	/*ADC prescaler options*/
#if RCC_ADC_PRESCALER==RCC_PRESCALER_2
   	CLR_BIT(RCC_CFGR,RCC_CFGR_ADCPRE0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_ADCPRE1);
#elif RCC_ADC_PRESCALER==RCC_PRESCALER_4
   	SET_BIT(RCC_CFGR,RCC_CFGR_ADCPRE0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_ADCPRE1);
#elif RCC_ADC_PRESCALER==RCC_PRESCALER_6
   	CLR_BIT(RCC_CFGR,RCC_CFGR_ADCPRE0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_ADCPRE1);
#elif RCC_ADC_PRESCALER==RCC_PRESCALER_8
   	SET_BIT(RCC_CFGR,RCC_CFGR_ADCPRE0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_ADCPRE1);
#else
#error"ADC PRESCALER OPTION IS NOT VALID"
#endif
/*APB2 Prescaler options*/
#if RCC_APB2_PRESCALER==RCC_PPRE2_PRESCALER_0
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE2_2);
#elif RCC_APB2_PRESCALER==RCC_PPRE2_PRESCALER_2
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE2_0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE2_1);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE2_0);
#elif RCC_APB2_PRESCALER==RCC_PPRE2_PRESCALER_4
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE2_0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE2_1);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE2_0);
#elif RCC_APB2_PRESCALER==RCC_PPRE2_PRESCALER_8
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE2_0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE2_1);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE2_0);
#elif RCC_APB2_PRESCALER == RCC_PPRE2_PRESCALER_16
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE2_0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE2_1);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE2_0);
#else
#error"Option For APB2 Is Not Valid"
#endif
   	/*option for APB1 prescaler*/
#if RCC_APB1_PRESCALER==RCC_PPRE1_PRESCALER_0
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE1_2);
#elif RCC_APB1_PRESCALER==RCC_PPRE1_PRESCALER_2
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE1_0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE1_1);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE1_2);
#elif RCC_APB1_PRESCALER==RCC_PPRE1_PRESCALER_4
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE1_0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE1_1);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE1_2);
#elif RCC_APB1_PRESCALER==RCC_PPRE1_PRESCALER_8
   	CLR_BIT(RCC_CFGR,RCC_CFGR_PPRE1_0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE1_1);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE1_2);
#elif RCC_APB1_PRESCALER==RCC_PPRE1_PRESCALER_16
    SET_BIT(RCC_CFGR,RCC_CFGR_PPRE1_0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE1_1);
   	SET_BIT(RCC_CFGR,RCC_CFGR_PPRE1_2);
#else
#error"options Not Valid"
#endif
   	/*Options For AHB*/
#if RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_0
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
#elif RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_2
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE4);
#elif RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_4
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE4);
#elif RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_8
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE4);
#elif RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_16
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE4);
#elif RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_64
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE4);
#elif RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_128
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE4);
#elif RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_256
   	CLR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE4);
#elif RCC_AHB_PRESCALER==RCC_HPRE_PRESCALER_512
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
   	SET_BIT(RCC_CFGR,RCC_CFGR_HPRE4);
#else
#error"options Is Not Valid"
#endif

}
void MRCC_VidEnableSystemClock(uint8 copy_uint8BusID,uint8 copy_uint8PerpheralID)
{

	if(copy_uint8PerpheralID<=31)
	{
		switch(copy_uint8BusID)
		{
		case RCC_AHB:
		{
			SET_BIT(RCC_AHBENR,copy_uint8PerpheralID);
			break;
		}
		case RCC_APB1:
		{
			SET_BIT(RCC_APB1ENR,copy_uint8PerpheralID);
			break;
		}
		case RCC_APB2:
		{
			SET_BIT(RCC_APB2ENR,copy_uint8PerpheralID);
			break;
		}
		default:
			break;
		}
	}
}
void MRCC_VidDisableSystemClock(uint8 copy_uint8BusID,uint8 copy_uint8PerpheralID)
{
	if(copy_uint8PerpheralID<=31)
		{
			switch(copy_uint8BusID)
			{
			case RCC_AHB:
			{
				CLR_BIT(RCC_AHBENR,copy_uint8PerpheralID);
				break;
			}
			case RCC_APB1:
			{
				CLR_BIT(RCC_APB1ENR,copy_uint8PerpheralID);
				break;
			}
			case RCC_APB2:
			{
				CLR_BIT(RCC_APB2ENR,copy_uint8PerpheralID);
				break;
			}
			default:
				break;
			}
		}
}


